import Foundation

public struct PasteboardSnapshot: Sendable {
    public let changeCount: Int
    public let text: String?
    public let isImage: Bool
    public let ignored: Bool

    public init(changeCount: Int, text: String?, isImage: Bool, ignored: Bool) {
        self.changeCount = changeCount
        self.text = text
        self.isImage = isImage
        self.ignored = ignored
    }
}

public enum PasteboardRules {
    public static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.apple.is-remote-clipboard",
    ]

    public static func shouldIgnore(typeNames: [String]) -> Bool {
        for name in typeNames {
            if ignoredTypes.contains(name) { return true }
        }
        return false
    }
}
